### ISSUE TITLE
I can't open it correctly,  when I opened it，there is a '-' in path, but in my base path, there is no '-'

### ISSUE THREAD

**Issue by xiangdongbu** [aberonni/open-in-vscode#18] opened 2023-03-27 09:07 UTC

**Comment by aberonni** [comment] 2023-03-27 19:11
What link are you trying to open?

**Comment by xiangdongbu** [comment] 2023-03-28 06:15
> What link are you trying to open?

Link like this：https://gitlab.xxxxx.com/xxxx-it/-/tree/develop

**Comment by xiangdongbu** [comment] 2023-03-28 09:45
> What link are you trying to open?

Or like this: https://gitlab.xxxxx.com/xxxx-it/-/tree/develop/packages/test/src/pages/home/index.tsx

Neither of them worked

**Comment by aberonni** [comment] 2023-03-28 10:23
Closing as a duplicate of #15 - feel free to reopen if the issue is a different one

**Closed** 2023-03-28 10:23 UTC
