### ISSUE TITLE
Not working with linux[Ubuntu]

### ISSUE THREAD

**Issue by dsairam17** [aberonni/open-in-vscode#2] opened 2019-10-10 06:55 UTC
I tried to open a .md file from github. But it fails to create a directory and store that file locally. So, I get an error that "Path does not exist".

**Comment by aberonni** [comment] 2019-10-10 08:50
Thanks for reporting! I don't have access to a linux machine right now, nor time to look into this properly :(

But I would be very happy to look into a MR that addresses this!

**Comment by aberonni** [comment] 2021-02-18 08:04
I actually just realised that this is probably a duplicate of https://github.com/aberonni/open-in-vscode/issues/5

**Closed by aberonni** 2021-02-18 08:04 UTC
